export const BALING_SHEET_NAMES = {
  production: "Bales_Production",
  failed: "Failed_Bales",
  scrap: "Scrap_Sidewalls",
  crca: "CR_CA_Tests",
  summaries: "Daily_Summaries",
  validation: "Validation_Log",
};

export const BALING_PRODUCTION_HEADERS = [
  "Chat Date Parsed",
  "Baling Machine Number",
  "Bale Number",
  "Record Type",
  "Production Type",
  "Baler Operator",
  "Baler Assistant Operator",
  "Start Time",
  "Finish Time",
  "Total Time to Bale",
  "Passenger",
  "4 x 4",
  "LC",
  "Motorcycle Qty",
  "SR Qty",
  "Agri Qty",
  "Tread Qty",
  "Side Wall Qty",
  "Other Item Raw",
  "Total Qty",
  "Weight Kg",
  "Notes / Flags",
  "Raw Message",
];

export const BALING_FAILED_HEADERS = [
  "Chat Date Parsed",
  "Baling Machine Number",
  "Bale Number",
  "Failure Type",
  "Failure Reason",
  "Baler Operator",
  "Baler Assistant Operator",
  "Start Time",
  "Finish Time",
  "Passenger Qty",
  "4x4 Qty",
  "LC Qty",
  "Motorcycle Qty",
  "SR Qty",
  "Agri Qty",
  "Tread Qty",
  "Side Wall Qty",
  "Total Qty",
  "Weight Kg",
  "Notes / Flags",
  "Raw Message",
];

export const BALING_SCRAP_HEADERS = [
  "Chat Date Parsed",
  "Baling Machine Number",
  "Production Label",
  "Bale Number",
  "Scrap Type",
  "Scrap Qty",
  "Weight Kg",
  "Baler Operator",
  "Baler Assistant Operator",
  "Start Time",
  "Finish Time",
  "Notes / Flags",
  "Raw Message",
];

export const BALING_CRCA_HEADERS = [
  "Chat Date Parsed",
  "Baling Machine Number",
  "Bale/Test Code",
  "Test Type",
  "Record Type",
  "Baler Operator",
  "Baler Assistant Operator",
  "Start Time",
  "Finish Time",
  "Total Time to Bale",
  "Tread Qty",
  "Side Wall Qty",
  "Passenger Qty",
  "4x4 Qty",
  "LC Qty",
  "Motorcycle Qty",
  "SR Qty",
  "Agri Qty",
  "Weight Kg",
  "Notes / Flags",
  "Raw Message",
];

export const BALING_SUMMARY_HEADERS = [
  "Chat Date Parsed",
  "Summary Type",
  "Baling Machine Number",
  "Bale Count",
  "Weight Kg",
  "Tons",
  "Passenger Qty",
  "4x4 Qty",
  "LC Qty",
  "Motorcycle Qty",
  "SR Qty",
  "Tread Qty",
  "Side Wall Qty",
  "Agri Qty",
  "Total Tyres",
  "Machine 1 Start Hour",
  "Machine 1 Finish Hour",
  "Machine 2 Start Hour",
  "Machine 2 Finish Hour",
  "Notes / Flags",
  "Raw Message",
];

export const BALING_CATEGORY_ALIASES = [
  { key: "passenger", pattern: /\bpassengers?\b|\bpass\b|\bpcr\b/i },
  { key: "fourx4", pattern: /\b4\s*x\s*4\b|\b4x4\b/i },
  { key: "lc", pattern: /\blight\s*commercials?\b|\blight\s*comm\b|\blc\b/i },
  { key: "motorcycle", pattern: /\bmotor\s*cycle\b|\bmotorcycle\b|\bmc\b/i },
  { key: "sr", pattern: /\bsr\b|\bside\s*wall\s*radial\b|\bradial\s*side\s*wall\b|\bhc\s*\(\s*ps\s*\)\b/i },
  { key: "agri", pattern: /\bagri\b|\bagricultural\b/i },
  { key: "tread", pattern: /\btyre\s*treads?\b|\btire\s*treads?\b|\btreads?\b|\blct\b|\bhct\b|\bhc\s*\(\s*treads?\s*\)\b/i },
  { key: "sideWall", pattern: /\bside\s*walls?\b|\bsidewall\b|\bsw\b/i },
];
