import { CUTTING_FIELD_HEADER_ROW, CUTTING_GROUP_HEADER_ROW, CUTTING_GROUP_MERGES } from "../cuttingSheetBuilder.js";

export const CUTTING_HEADERS = CUTTING_FIELD_HEADER_ROW;
export const CUTTING_GROUP_HEADERS = CUTTING_GROUP_HEADER_ROW;
export const CUTTING_HEADER_MERGES = CUTTING_GROUP_MERGES;
